development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: lab5-vvss_development
  pool:     5
  username: anca
  password: root
  template: template0

test: &test
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: lab5-vvss_test
  pool:     5
  username: anca
  password: root
  template: template0

cucumber:
  <<: *test
